[package]
name = "link"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
sqlx = {version = "0.7.4", features= ["tls-native-tls", "postgres", "runtime-tokio"]}
tokio = {version ="1.38", features = ["full"]}
serde ="1.0"
serde_json = "1.0"